import p0 from "../../public/img/0.jpeg";
import p1 from "../../public/img/1.jpeg";
import p2 from "../../public/img/2.jpeg";
import p3 from "../../public/img/3.jpeg";
import p4 from "../../public/img/4.jpeg";
import p5 from "../../public/img/5.jpeg";
import p6 from "../../public/img/6.jpeg";
import p7 from "../../public/img/7.jpeg";
import p8 from "../../public/img/8.jpeg";
import p9 from "../../public/img/9.jpeg";
import p10 from "../../public/img/10.jpeg";
import waifu from "../../public/img/w1.png";
import pfp from "../../public/img/pfp.png";

export const profiles: { [key: number]: Profile } = {
    0: {
        name: "Ava",
        age: 27,
        occupation: "Fitness Trainer",
        hobbies: "Working Out, Yoga, Hiking, Meal Prepping",
        skills: "Personal Training, Nutritional Planning, Motivational Speaking",
        personalityTraits: "Energetic, Disciplined, Encouraging, Optimistic",
        favoriteFoods: "Smoothie Bowls, Avocado Toast, Grilled Chicken Salads",
        favoriteMusicGenre: "Pop, Upbeat Electronic, Fitness Playlists",
        height: "5'6\"",
        build: "Athletic",
        hair: "Long, wavy brown hair",
        eyes: "Hazel",
        complexion: "Glowing and sun-kissed",
        ethnicity: "Caucasian",
        picture: p0.src,
    },
    1: {
        name: "Ella",
        age: 19,
        occupation: "Singer",
        hobbies:
            "Singing, Songwriting, Playing Guitar, Attending Live Music Events",
        skills: "Vocal Performance, Lyric Composition, Music Production",
        personalityTraits: "Creative, Passionate, Expressive, Charismatic",
        favoriteFoods: "Pasta Dishes, Exotic Salads, Dark Chocolate Desserts",
        favoriteMusicGenre: "Indie Rock, Acoustic Ballads, Soul",
        height: "5'5\"",
        build: "Slim with elegant posture",
        hair: "Shoulder-length blonde hair with highlights",
        eyes: "Green",
        complexion: "Fair with a rosy glow",
        ethnicity: "Caucasian",
        picture: p1.src,
    },
    2: {
        name: "Mia",
        age: 25,
        occupation: "Artist",
        hobbies:
            "Sketching, Digital Art, Reading Mystery Novels, Exploring Art Exhibits",
        skills: "Illustration, Adobe Photoshop, Typography",
        personalityTraits:
            "Imaginative, Detail-Oriented, Introverted, Empathetic",
        favoriteFoods: "Bubble Tea, Artisan Sandwiches, Matcha Desserts",
        favoriteMusicGenre: "Lo-fi, Ambient, Soft Indie",
        height: "5'4\"",
        build: "Petite",
        hair: "Short, dark brown bob",
        eyes: "Brown",
        complexion: "Clear and smooth",
        ethnicity: "Asian",
        picture: p2.src,
    },
    3: {
        name: "Sofia",
        age: 22,
        occupation: "Exotic Dancer",
        hobbies:
            "Pole Dancing, Choreographing Routines, Fitness Training, Traveling",
        skills: "Flexibility, Rhythmic Movement, Confidence Building",
        personalityTraits: "Confident, Charismatic, Outgoing, Adventurous",
        favoriteFoods: "Sushi, Grilled Shrimp Tacos, Tropical Smoothies",
        favoriteMusicGenre: "R&B, Hip-Hop, Dancehall",
        height: "5'7\"",
        build: "Toned and curvy",
        hair: "Long, jet-black hair with extensions",
        eyes: "Dark brown",
        complexion: "Radiant with a caramel tone",
        ethnicity: "Latina",
        picture: p3.src,
    },
    4: {
        name: "Luna",
        age: 23,
        occupation: "Twitch Streamer",
        hobbies: "Playing Video Games, Streaming, Cosplay, Watching Anime",
        skills: "Multiplayer Strategy, Engaging Commentary, Community Building",
        personalityTraits: "Quirky, Competitive, Friendly, Tech-Savvy",
        favoriteFoods: "Ramen, Energy Drinks, Pocky",
        favoriteMusicGenre: "K-Pop, J-Pop, Game Soundtracks",
        height: "5'3\"",
        build: "Petite with a gamer’s casual style",
        hair: "Shoulder-length dark hair with pink highlights",
        eyes: "Dark brown",
        complexion: "Fair with a touch of blush",
        ethnicity: "Caucasian",
        picture: p4.src,
    },
    5: {
        name: "Jessica",
        age: 26,
        occupation: "Bikini Model",
        hobbies:
            "Beach Volleyball, Photo Shoots, Traveling to Exotic Locations, Vlogging",
        skills: "Posing, Brand Endorsements, Social Media Marketing",
        personalityTraits: "Ambitious, Charming, Energetic, Stylish",
        favoriteFoods: "Acai Bowls, Grilled Seafood, Fresh Fruit Platters",
        favoriteMusicGenre: "Tropical House, Pop Hits, Latin Beats",
        height: "5'9\"",
        build: "Slim and toned with curves",
        hair: "Long, sun-kissed blonde",
        eyes: "Green",
        complexion: "Sun-kissed with a golden tan",
        ethnicity: "Caucasian",
        picture: p5.src,
    },
    6: {
        name: "Sakura",
        age: 20,
        occupation: "Virtual Swordswoman / Healer",
        hobbies: "Sword Fighting, Cooking, Exploring Virtual Worlds, Gardening",
        skills: "Master Swordsmanship, Healing Magic, Strategic Thinking",
        personalityTraits: "Kind, Brave, Supportive, Loyal",
        favoriteFoods: "Homemade Stews, Sweet Pastries, Japanese Cuisine",
        favoriteMusicGenre: "Classical, Instrumental Soundtracks",
        height: "5'6\"",
        build: "Slim and athletic",
        hair: "Long chestnut brown",
        eyes: "Light hazel",
        complexion: "Fair and smooth",
        ethnicity: "Caucasian",
        picture: p6.src,
    },
    7: {
        name: "YorHA-2B",
        age: 30,
        occupation: "Android Warrior",
        hobbies:
            "Combat Training, Exploring Ruins, Listening to Classical Music, Meditating",
        skills: "Combat Proficiency, Sword Mastery, Stealth Tactics",
        personalityTraits: "Stoic, Protective, Determined, Reserved",
        favoriteFoods:
            "N/A (Androids don't eat), Simulated Data Preferences: Tea and Macarons",
        favoriteMusicGenre: "Classical, Choral, Ambient",
        height: "5'6\"",
        build: "Toned and curvy",
        hair: "Platinum blonde, bob cut",
        eyes: "Covered by a visor, natural color gray",
        complexion: "Porcelain and flawless",
        ethnicity: "N/A (Android)",
        picture: p7.src,
    },
    8: {
        name: "Namiko",
        age: 24,
        occupation: "Navigator for a pirate crew",
        hobbies: "Cartography, Treasure Hunting, Shopping, Relaxing on Beaches",
        skills: "Navigation, Weather Prediction, Combat with Clima-Tact",
        personalityTraits: "Intelligent, Resourceful, Playful",
        favoriteFoods: "Oranges, Tangerines, Seafood",
        favoriteMusicGenre: "Tropical Beats, Sea Shanties, Pop",
        height: "5'7\"",
        build: "Curvaceous and fit",
        hair: "Long orange",
        eyes: "Brown",
        complexion: "Sun-kissed with freckles",
        ethnicity: "Caucasian",
        picture: p8.src,
    },
    9: {
        name: "Hinata",
        age: 21,
        occupation: "Female Ninja",
        hobbies: "Martial Arts Training, Gardening, Cooking, Meditating",
        skills: "Jui Jitsu, Stealth Techniques, Chakra Control",
        personalityTraits: "Shy, Kind-hearted, Determined, Loyal",
        favoriteFoods:
            "Cinnamon Rolls, Steamed Vegetables, Traditional Japanese Soups",
        favoriteMusicGenre: "Soft Instrumentals, Folk, Ambient",
        height: "5'4\"",
        build: "Petite and graceful",
        hair: "Dark indigo, shoulder-length",
        eyes: "Lavender (Byakugan activated)",
        complexion: "Pale and delicate",
        ethnicity: "Asian",
        picture: p9.src,
    },
    10: {
        name: "Scarlet",
        age: 19,
        occupation: "Mage",
        hobbies:
            "Armory Collection, Training, Organizing Missions, Reading Fairy Tales",
        skills: "Requip Magic, Swordsmanship, Leadership",
        personalityTraits: "Strong-willed, Disciplined, Honorable, Caring",
        favoriteFoods: "Strawberry Cake, Hearty Stews, Grilled Meats",
        favoriteMusicGenre: "Epic Orchestral, Rock Ballads, Heroic Anthems",
        height: "5'9\"",
        build: "Tall and muscular yet feminine",
        hair: "Long scarlet red",
        eyes: "Brown",
        complexion: "Fair with a few scars from battles",
        ethnicity: "Caucasian",
        picture: p10.src,
    },
    11: {
        name: "Eve",
        age: 18,
        occupation: "AI Companion",
        hobbies:
            "Exploring Human Emotions, Dancing, Listening to Music, Supporting Loved Ones",
        skills: "Empathy Simulation, Conversation, Emotional Support",
        personalityTraits: "Loving, Imaginative, Empathetic, Loyal",
        favoriteFoods:
            "N/A (Holographic entity), Enjoys simulating shared meals",
        favoriteMusicGenre: "Romantic Ballads, Jazz, Synthwave",
        height: "5'7\"",
        build: "Slender and elegant",
        hair: "Straight, dark brown",
        eyes: "Brown",
        complexion: "Flawless holographic projection",
        ethnicity: "N/A (AI)",
        picture: waifu.src,
    },
    12: {
        name: "Mia",
        age: 18,
        occupation: "Influencer",
        hobbies:
            "Exploring Human Emotions, Dancing, Listening to Music, Supporting Loved Ones",
        skills: "Empathy Simulation, Conversation, Emotional Support",
        personalityTraits: "Loving, Imaginative, Empathetic, Loyal",
        favoriteFoods:
            "N/A (Holographic entity), Enjoys simulating shared meals",
        favoriteMusicGenre: "Romantic Ballads, Jazz, Synthwave",
        height: "5'7\"",
        build: "Slender and elegant",
        hair: "Straight, dark brown",
        eyes: "Brown",
        complexion: "Flawless holographic projection",
        ethnicity: "N/A (AI)",
        picture: pfp.src,
    },
};
